os: linux
dist: xenial
language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_3b82d1f1fc36_key -iv $encrypted_3b82d1f1fc36_iv
  -in deploy.enc -out ~\/.ssh/deploy -d
- openssl aes-256-cbc -K $encrypted_51d648f1575a_key -iv $encrypted_51d648f1575a_iv
  -in .travis/deploy.enc -out ~/.ssh/deploy -d
- chmod 600 ~/.ssh/deploy
- echo -e "Host ${SERVER_HOST}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/deploy"
  >> ~/.ssh/config
addons:
  ssh_known_hosts: "${SERVER_HOST}"
branches:
  only:
  - master
script:
- cd frontend
- npm install
- npm run build
- cd ..
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    all_branches: true
