os: linux
dist: xenial
language: node_js
node_js: stable

before_install:
  - openssl aes-256-cbc -K $encrypted_3b82d1f1fc36_key -iv $encrypted_3b82d1f1fc36_iv -in .travis/deploy.enc -out ~/.ssh/deploy -d
  - chmod 600 ~/.ssh/deploy
  - echo -e "Host ${SERVER_HOST}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/deploy" >> ~/.ssh/config

addons:
  ssh_known_hosts: "${SERVER_HOST}"

branches:
  only:
  - master

script:
  - unset CI
  - cd frontend
  - npm install
  - npm run build
  - cd ..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    all_branches: true
