# This workflow will Update the API Documentation Page

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths: [backend/controllers/*]
  pull_request:
    branches: [ master ]
    paths: [backend/controllers/*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Create Doc
      run: |
        npm install apidoc -g
        apidoc -i backend/controllers/ -o docs/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/*
        git commit -m "Upadte API Documentation [ci-skip]"
        
    - name: Push new Doc Github Page
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ github.token }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: ${GITHUB_REPOSITORY}

    
    
